### PR TITLE
feat: Add Youssouph as a contributor

### PR DESCRIPTION
**Pull request by maney-dev**
## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [ ] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### How did you add yourself as a contributor?

- [ ] 🤖 With CLI
- [x] ⌨️ Manually

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [x] ✅ Yes
- [ ] ❌ No

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [x] 🙅 no documentation needed

## Screenshot
Open-source-me

### CODE REVIEW

**Review by takanome-dev — APPROVED** [review]
LGTM 👍

**Comment by BekahHW** [comment]
Hey @youssoph-mane can you add a screenshot to your PR form? That's required for a review.

**Review by BekahHW — APPROVED** [review]

**Comment by takanome-dev** [comment]
cc @CBID2, needs another approval to merge this 🙂

**Comment by CBID2** [comment]
> cc @CBID2, needs another approval to merge this 🙂

Not yet @takanome-dev. @maney-dev, can you fill out the description section of your PR form?
Here's what you need to do:

**Comment by BekahHW** [comment]
> > cc @CBID2, needs another approval to merge this 🙂
> 
> Not yet @takanome-dev. @maney-dev, can you fill out the description section of your PR form? Here's what you need to do:
> 
> ```
> ## Description
> Add this here: This PR adds <your github-username> as a contributor. 
> ```

@CBID2 it doesn't say required and doesn't give directions in the course to add the description. I think the title is descriptive enough here.

**Comment by CBID2** [comment]
> > > cc @CBID2, needs another approval to merge this 🙂
> 
> > 
> 
> > Not yet @takanome-dev. @maney-dev, can you fill out the description section of your PR form? Here's what you need to do:
> 
> > 
> 
> > ```
> 
> > ## Description
> 
> > Add this here: This PR adds <your github-username> as a contributor. 
> 
> > ```
> 
> 
> 
> @CBID2 it doesn't say required and doesn't give directions in the course to add the description. I think the title is descriptive enough here.

Ok then @BekahHW

**Review by CBID2 — APPROVED** [review]
Thanks for contributing @maney-dev

**Pull request merged**
