### PR TITLE
docs: add @nickaldwin as a contributor

### PR DESCRIPTION
**Pull request by nickaldwin**
## Description
Add nickaldwin as a Contributor

## What type of PR is this? (check all applicable)

- [X] 🤝 Add a contributor
- [ ] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [X] ✅ Yes
- [ ] ❌ Not yet

### How did you add yourself as a contributor?

- [X] 🤖 With CLI
- [ ] ⌨️ Manually

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [X] ✅ Yes
- [ ] ❌ No

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [X] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [X] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot
Screenshot_2024-02-01_13-01-59

## [optional] What GIF best describes this PR or how it makes you feel?
😊

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @nickaldwin! :) Thanks for contributing to our project. I noticed that you did not fill out the screenshot section of your PR. Can you do that please? If you need help, check out [step 8 in the "Let's Get Practical section in the intro course](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source).

**Comment by nickaldwin** [comment]
@CBID2 apologies i will add the screenshot

**Comment by nickaldwin** [comment]
Screenshot_2024-02-01_12-52-46

**Comment by nickaldwin** [comment]
Screenshot_2024-02-01_13-01-59

**Comment by CBID2** [comment]
> @CBID2 apologies where do i attach the screenshot?
You place it before the GIF section @nickaldwin 
screenshot of screenshot section

**Comment by nickaldwin** [comment]
@CBID2 thank you

**Review by CBID2 — APPROVED** [review]
Looks good to me. What do you think @adiati98?

**Comment by adiati98** [comment]
Hey @nickaldwin 
Thanks for the PR!

Can you please fill in the "Description" section in the PR form?
It's needed for us to understand the details of the changes that you made. Thank you. 😊

**Comment by nickaldwin** [comment]
Hi @adiati98 i update it thank you so much 😊

**Comment by adiati98** [comment]
> Hi @adiati98 i update it thank you so much 😊

You're welcome! Please let me know once you've filled it in. 👍

**Comment by nickaldwin** [comment]
Hi @adiati98 I'm so sorry if i skip to read the first comment i updated it

**Review by adiati98 — APPROVED** [review]
Well done, @nickaldwin! 🙌
Thank you for completing the PR form! 😄

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕 

git merge GIF

**Comment by nickaldwin** [comment]
@adiati98 thank you so much 🎉🎉🎉♥️♥️♥️

**Pull request merged**
