### PR TITLE
docs: add @Emmarie-Ahtunan as a contributor

### PR DESCRIPTION
**Pull request by Emmarie-Ahtunan**
## Description

This PR adds me as a contributor to the guestbook. 

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by adiati98** [comment]
Hi @Emmarie-Ahtunan 
Thank you for your PR!

But you missed the step to run the `npm run contributors:generate` to update the README.
Please see step no. 6 the [Getting Started](npm run contributors:generate) section.

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hi @Emmarie-Ahtunan 
Thank you for your PR!

But you missed the step to run the `npm run contributors:generate` to update the README.
Please see step no. 6 the [Getting Started](https://github.com/open-sauced/guestbook#getting-started) section.

**Comment by adiati98** [comment]
@Emmarie-Ahtunan 
We have merged a PR before yours. So while you're making changes, please also [resolve the conflicts](https://github.com/open-sauced/guestbook#keeping-branch-up-to-date-and-resolving-merge-conflicts) before we can merge yours.

Please let us know if you need any help :)

**Comment by Emmarie-Ahtunan** [comment]
Hello @adiati98 I tried running the npm run contributors:generate again this morning and it's deleting a lot of the README.md file. I'm not sure what to do, can you help please?

**Comment by adiati98** [comment]
Hi @Emmarie-Ahtunan,
You've closed this PR so I can't see the changes you made 😅

So I see you force-pushed your branch.
Can you let me know the current state there?

**Comment by adiati98** [comment]
Let me reopen this PR so I can walk you through, @Emmarie-Ahtunan :)

**Comment by Emmarie-Ahtunan** [comment]
I just fixed it and added a new PR that I think works.

**Comment by adiati98** [comment]
Awesome, @Emmarie-Ahtunan!
Can you revert this draft to ready for review?

**Comment by Emmarie-Ahtunan** [comment]
I synced my fork to not have a merge conflict. So these files are deleted. May I see if I can comment on my current "conflicting" PR?

**Comment by adiati98** [comment]
> I synced my fork to not have a merge conflict. So these files are deleted. May I see if I can comment on my current "conflicting" PR?

Sorry, I don't catch you. Which files are deleted? I mean, I see both files here.

**Comment by Emmarie-Ahtunan** [comment]
I just did, with the updated changes. I apologize and also thank you so very much @adiati98!

**Review by adiati98 — APPROVED** [review]
It looks good! Well done, @Emmarie-Ahtunan! 🙌

I see that you have contributed to our `pizza-verse` repo! Thank you for your contributions😄
If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P) 😊

**Comment by adiati98** [comment]
> I just did, with the updated changes. I apologize and also thank you so very much @adiati98!

No need to apologize, @Emmarie-Ahtunan! 😄

Did you use our docs to resolve conflicts?
If so, may I ask for your feedback if they're clear enough?
TIA! 😊

**Comment by Emmarie-Ahtunan** [comment]
Yay! I'm so very excited ... thank you so much @adiati98! Yes, I've joined the Discord already and I have some more changes to make to the pizza-verse contribution before it can be merged but this one is golden; tysvm!

**Comment by Emmarie-Ahtunan** [comment]
> > I just did, with the updated changes. I apologize and also thank you so very much @adiati98!
> 
> No need to apologize, @Emmarie-Ahtunan! 😄
> 
> Did you use our docs to resolve conflicts? If so, may I ask for your feedback if they're clear enough? TIA! 😊

Your docs are clear enough, yes. I read them, especially for the PR request documentation on my pizza-verse PRs but I still don't understand what I need to change for that. Open-sauced is AMAZING!!!

**Comment by adiati98** [comment]
> > > I just did, with the updated changes. I apologize and also thank you so very much @adiati98!
> > 
> > 
> > No need to apologize, @Emmarie-Ahtunan! 😄
> > Did you use our docs to resolve conflicts? If so, may I ask for your feedback if they're clear enough? TIA! 😊
> 
> Your docs are clear enough, yes. I read them, especially for the PR request documentation on my pizza-verse PRs but I still don't understand what I need to change for that. Open-sauced is AMAZING!!!

Thank you so much for your feedback, @Emmarie-Ahtunan! 💙
We hope we see you around for another contributions! 🙌

**Pull request merged**
