### PR TITLE
Feat(PR Template): Update PULL_REQUEST_TEMPLATE.md to emphasize compulsory screenshot

### LINKED ISSUE #223: docs: Clarity about screenshot
### Type of feature

🍕 Feature

### Current behavior

Contributors have been skipping the screenshot section when filling out their PR form. It’s mostly likely due to assuming that’s it’s not required inspite of the course mentioning that it’s needed. 

### Suggested solution

1. Go the `.github` folder
2. Go to the `Pull Request` file 
3. On line 39, next to `Screenshot`, write "(*Required before Pull Request is Reviewed)" 

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by ArvindParekh**
## Description

Fixes #223 

## What type of PR is this? (check all applicable)

- [ ] 🤝 Add a contributor
- [x] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### How did you add yourself as a contributor?

- [ ] 🤖 With CLI
- [ ] ⌨️ Manually

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [ ] ✅ Yes
- [x] ❌ No

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [ ] ✅ Yes
- [x] ❌ No

## Added to documentation?

- [ ] 📜 README.md
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by ArvindParekh** [comment]
I've updated the wording `(*Required before Pull Request is Reviewed)` (suggested in the issue) to `(Required for PR Review)` to try to be concise and clear.
Let me know and I'd be happy to change that back.

Also, I noticed this comment just below the `Screenshot` section, which I think can be further improved:
```diff
+ <!-- Please provide a screenshot of your profile being generated on the README. This ensures that you ran the `npm run contributors:generate` command, as mentioned in the previous question, and it makes it easier for maintainers to review PRs. All PRs without screenshots will be automatically rejected-->
- <!-- Please provide a screenshot of your profile being generated on the README. This ensures that you run the `npm run contributors:generate` command, as mentioned in the previous question, and makes it easier for maintainers to review PRs. All PRs without screenshots will be automatically rejected-->
```

I'd like to know your thoughts on this, thanks!

**Comment by CBID2** [comment]
> I've updated the wording `(*Required before Pull Request is Reviewed)` (suggested in the issue) to `(Required for PR Review)` to try to be concise and clear.
> 
> Let me know and I'd be happy to change that back.
> 
> 
> 
> Also, I noticed this comment just below the `Screenshot` section, which I think can be further improved:
> 
> ```diff
> 
> + 
> 
> - 
> 
> ```
> 
> 
> 
> I'd like to know your thoughts on this, thanks!

Hi @ArvindParekh. I think the improvement you made on the looks good.

**Review by CBID2 — APPROVED** [review]
Looks good on my end. What do you think @BekahHW?

**Comment by BekahHW** [comment]
@ArvindParekh, sure! Go ahead and improve the line you mentioned and then @ me for another review. Everything looks good rn.

**Comment by CBID2** [comment]
> @ArvindParekh, sure! Go ahead and improve the line you mentioned and then @ me for another review. Everything looks good rn. 

Hey @BekahHW, it looks like @ArvindParekh made the change already
image

**Comment by ArvindParekh** [comment]
@CBID2 Oh no, it isn't done yet. I suggested changing the `run` to `ran` and adding an extra `it` in the sentence to make it more understandable and meaningful. I'll do the changes now.

**Comment by CBID2** [comment]
> @CBID2 Oh no, it isn't done yet. I suggested changing the `run` to `ran` and adding an extra `it` in the sentence to make it more understandable and meaningful. I'll do the changes now.

Thanks for clarifying @ArvindParekh

**Comment by ArvindParekh** [comment]
@BekahHW I've pushed the changes 👍🏻

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
