### PR TITLE
twister904 committed

### PR DESCRIPTION
**Pull request by twister904**
## Description
I have taken the initiative to contribute to the OpenSauced project by manually adding my details to the guestbook. I am committed to learning more about open source and becoming an active member of this community.

In this pull request, I have made the necessary changes to the guestbook, providing my information and showing my commitment to being a part of this open source journey. By accepting this pull request, I hope to gain more experience and knowledge about open source development while actively participating in the OpenSauced project.

I appreciate the opportunity to contribute and look forward to your feedback and guidance on this journey. Thank you for considering my pull request.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [x] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

feat: add {twister904} as a contributor

### CODE REVIEW

**Comment by adiati98** [comment]
Hi @twister904,
Thank you for your PR!

Can you please fill in the pull request form accordingly (the description, etc.)?
This would help the maintainers to review your PR better.
Thanks 🙂

**Comment by adiati98** [comment]
> okay i will fill out the form ..

Only need the description here :)
Fill out the description is very important for maintainers to understand what changes you make in your PR.

**Comment by twister904** [comment]
i understand i have have filled the description please have a look on the description

**Review by adiati98 — APPROVED** [review]
Well done, @twister904! 🙌
Thank you for the PR! 😄

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕 

git merge GIF

**Comment by twister904** [comment]
Thank you so much! These things have made my day. 
WoohooYeahGIF

**Comment by twister904** [comment]
please add hacktoberfest accepted label on this PR

**Pull request merged**
