### PR TITLE
docs: update @droffilc1 as a contributor

### PR DESCRIPTION
**Pull request by droffilc1**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by BekahHW** [comment]
Hey @droffilc1! You've got some merge conflicts happening after I merged in the other PRs. Let me know if you need help with this.

**Comment by droffilc1** [comment]
Hey @BekahHW, I need help

**Comment by BekahHW** [comment]
Hey @droffilc1 I realized that there was an issue with extra code that I merged in with the PR before you and that was part of the problem.

I went ahead and cleaned it up and accepted the changes so I was able to merge you in. Let me know if you want to pair up and I can walk you through what happened.

**Comment by droffilc1** [comment]
Hey @BekahHW I would like to pair up

**Comment by BekahHW** [comment]
Can you send me an email with your available times next week? Bekah@ OpenSauced.pizza.

**Comment by droffilc1** [comment]
Sure

**Pull request merged**
