### PR TITLE
Feature/obasoro kunle

### PR DESCRIPTION
**Pull request by Obasoro**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by Obasoro** [comment]
Discarded previous commits and added new `Add obasoro` as the commit message.

**Review by adiati98 — CHANGES_REQUESTED** [review]
@Obasoro "jayasuryard31" profile is still not added back. Once you fix this, we might be able to merge your PR.

**Comment by Obasoro** [comment]
Added `jayasuryard31` profile  back

**Review by adiati98 — APPROVED** [review]
@Obasoro thanks! 🎉

good job GIF

**Comment by Obasoro** [comment]
Thanks, @adiati98 @CBID2 for following through.

**Pull request merged**
