### PR TITLE
feat: Add RafaelJohn9 as a contributor

### LINKED ISSUE #312: Feature: Add @RafaelJohn9 as a contributor
### Description

As part of the Intro to Open Source course, students are encouraged to contribute to this repo.

### Suggested solution

Add @RafaelJohn9 as a contributor.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

### PR DESCRIPTION
**Pull request by RafaelJohn9**
## Description
I have added a new contributor (me) as per the open-sauced guide that closes the 

## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [ ] 📝 Documentation Update

## Related Issues

Closes #312 

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

Screenshot from 2024-04-25 11-55-34

## [optional] What GIF best describes this PR or how it makes you feel?
Gif

### CODE REVIEW

**Comment by RafaelJohn9** [comment]
@adiati98 I have fixed the issue

**Comment by RafaelJohn9** [comment]
on it

**Comment by RafaelJohn9** [comment]
@adiati98 its done

**Review by BekahHW — CHANGES_REQUESTED** [review]
Line 39 in the readme should also be updating:

`[All Contributors](#contributors-)`

Have you run `npm run contributors:generate`?

**Review by adiati98 — APPROVED** [review]
Hi @RafaelJohn9,
I've helped you run the generate command to increase the badge and generate your profile on README in your PR. ✨ 

Please pay attention to step 3 in [this section about how to resolve conflicts](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=keeping-branches-up-to-date). For your future contributions reference, you need to read instructions in any guidelines thoroughly.

I've also created an issue (#312) to accompany this PR. You can read [this blog post](https://dev.to/opensauced/streamline-your-contributions-mastering-issue-forms-and-pr-templates-36j5) about the importance of having an issue when contributing to open source projects.

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕

pizza GIF

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
