### PR TITLE
docs: add @geoffreylgv as a contributor

### PR DESCRIPTION
**Pull request by geoffreylgv**
## Description
Add myself as contributor to the guestbook

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by Sadeedpv — APPROVED** [review]

**Review by CBID2 — APPROVED** [review]
Looks good

**Comment by CBID2** [comment]
@geoffreylgv, we merged some PRs recently. Can you solve the merge conflicts in your branch? If you need a refresher, check out the blog post,[Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h)

**Comment by geoffreylgv** [comment]
> @geoffreylgv, we merged some PRs recently. Can you solve the merge conflicts in your branch? If you need a refresher, check out the blog post,[Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h)

Alright @CBID2 👍🏾

**Comment by CBID2** [comment]
Any updates on this @geoffreylgv?

**Comment by geoffreylgv** [comment]
> Any updates on this @geoffreylgv?

Yes, will push soon

**Comment by geoffreylgv** [comment]
@CBID2, I run to issues, check it out; I made the update

**Pull request merged**
