### PR TITLE
feat: Add @edwinhung as a contributor

### PR DESCRIPTION
**Pull request by edwinhung**
Add Edwin Hung as a contributor

### CODE REVIEW

**Review by CBID2 — CHANGES_REQUESTED** [review]
Thanks for your Pull Request @edwinhung! We've just merged in some new PRs so can you resolve the merge conflicts on your branch? If you need some help with that, check out our blog post [Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h).

**Comment by edwinhung** [comment]
Thank you @CBID2. I moved myself down to the end of contributors list in .all-contributorsrc and update README file accordingly. Let me know if there's other issue.

**Comment by CBID2** [comment]
@BekahHW, can you help review the changes?

**Review by BekahHW — APPROVED** [review]

**Comment by BekahHW** [comment]
@CBID2 I approved it. We just need you to remove your requested changes/approve so it can be merged in.

**Comment by CBID2** [comment]
Congratulations @edwinhuang! You just made your first contribution! 🥳 It was wonderful working with you! 😄 If you want to do more contributions, check out these issues in our pizza-verse repository. Also, join our Discord community to get more updates on OpenSauced and interact with other contributors! :) We'd love to have you! :)

**Pull request merged**
