### PR TITLE
feat: adding translation rules to README

### LINKED ISSUE #93: feat: add translation rules and guide to README
> @CBID2 I did look into Crowdin. I think we need to make sure there's interest. I'm super excited to have folks interested in translating, but we need to gauge how many people are _using_ the translated versions as part of the discussion. Maybe we should consider adding something to the PR template to ask them to select the language they used to complete the task.

That's a great idea! :) I do a PR for that part if you'd like.

_Originally posted by @CBID2 in https://github.com/open-sauced/guestbook/issues/79#issuecomment-1708705982_

### PR DESCRIPTION
**Pull request by CBID2**
## Description
In this PR, I added a translation guidelines section to the README file. This will encourage non-English or bilingual people an opportunity to contribute to the project, and fulfill one of our goals: to make this project more culturally-inclusive. 

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #93 
Relates to [#71](https://github.com/open-sauced/intro/issues/71?notification_referrer_id=NT_kwDOBkyZ8LQ4MDA4MjI2MzU5OjEwNTY4MzQ0MA#issuecomment-1756533448)
## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [X] 🙋 no, because I need help

## Added to documentation?

- [X] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## Note to Reviewers
I was heavily inspired by[Astro's Docs](https://github.com/withastro/docs/blob/main/.github/hacktoberfest.md#i18n-reviews-count) approach to encouraging translation contributions. Now I placed this in draft mode because I'm debating on whether to create the translating guide and add it to this PR or do it in another PR after this one is merged. Any feedback is helpful. 

## [optional] What gif best describes this PR or how it makes you feel?

[Rick from "Rick & Morty" looks confused](https://giphy.com/gifs/rickandmorty-season-2-adult-swim-rick-and-morty-ZFhhpKngh5QfcmhIDF)

### CODE REVIEW

**Review by BekahHW — APPROVED** [review]
LGTM!

**Comment by BekahHW** [comment]
@CBID2 as soon as you update your branch and change if from a draft PR, I think this is ready to be merged.

**Comment by ivansftdejc** [comment]
I am new to open source, how can I help with contribution?

**Comment by CBID2** [comment]
> I am new to open source, how can I help with contribution?

Hi @ivansftdejc. You've come to the right place! 😊 We have an intro course to help you get started: https://intro.opensauced.pizza/#/

**Pull request merged**
