### PR TITLE
Brandon added as a contributor

### PR DESCRIPTION
**Pull request by Bradondev**
## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor

## Contributors checklist (check all applicable)

- Have you read the [Getting Started](https://github.com/open-sauced/guestbook#getting-started) section thoroughly?

  - [x] ✅ Yes

- How did you add yourself as a contributor?

  - [x] ⌨️ Manually

    If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

 
    - [x] ❌ No

- Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
  - [x] ✅ Yes

## Added to documentation?

- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hi @Bradondev,
Thank you for your PR! 🙌

You need to generate your profile on the README by running the `npm run contributors:generate`.

Let me know when it's fixed and ready for a review.
Thank you. 🙂

**Comment by CBID2** [comment]
To add to my original comment @Bradondev, we've merged in some new PRs, so can you merge the latest changes and resolve conflicts? If you need some help with that, check out this post: [Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h).

**Comment by Bradondev** [comment]
Okay, will do that thanks for the help.

**Comment by CBID2** [comment]
> Okay, will do that thanks for the help.

You're welcome! You can also check out [this section in the README](https://github.com/open-sauced/guestbook/blob/main/README.md#keeping-branch-up-to-date-and-resolving-merge-conflicts)

**Comment by CBID2** [comment]
Hey @Bradondev. I fixed the merge conflicts. Don't forget to do `npm run contributors:generate` in your terminal.

**Comment by CBID2** [comment]
Hi @Bradondev! :) Are you going to work on this? :)

**Review by CBID2 — APPROVED** [review]
Hi @Bradondev! :) To move the merge process forward, I resolved your merge conflicts, generated the command. In the future, I highly recommend resolving your merge conflicts promptly. It'll make it easier for maintainers to review your contributions. Speaking of other projects and contributions, check out our [pizza-verse repo](https://github.com/open-sauced/pizza-verse) join our Discord server to get updates on OpenSauced and to see what other people are working on: https://discord.com/invite/U2peSNf23P

**Review by adiati98 — APPROVED** [review]

**Pull request merged**
