### PR TITLE
docs: add @skippharaoh as a contributor

### PR DESCRIPTION
**Pull request by SkipPharaoh**
## Description
This PR adds @SkipPharaoh as a contributor!

## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [ ] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### How did you add yourself as a contributor?

- [ ] 🤖 With CLI
- [x] ⌨️ Manually

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [x] ✅ Yes
- [ ] ❌ No

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

Screen Shot 2024-04-09 at 6 17 45 PM

## [optional] What GIF best describes this PR or how it makes you feel?
😃 😀  Feel good to contribute to Open Sauced!

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hey @SkipPharaoh,
Thank you for your PR! ✨

We have merged a PR before yours. Please [resolve the conflicts](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=merge-conflicts-in-the-guestbook-repository) before we can merge yours.

Also, please fill in the "Description" section and complete the PR form.
Incomplete PR form will be marked invalid.

Do let us know if you need any help. Thanks. 😊

**Comment by SkipPharaoh** [comment]
@adiati98 I went ahead & resolved the conflicts. I also added a description to the PR. I'm not too sure what else I need to do to complete the PR form. I looked through another merged PR to double check & I don't think I'm missing anything else. 

Please point me in the right direction if I missed something.

**Comment by adiati98** [comment]
Hi @SkipPharaoh 
Your PR form is completed 😊

But I see that you haven't run the generate command after resolving conflicts.

Can you please do that? You can refer to step 3 in the [Resolving Merge Conflicts] section.

**Comment by SkipPharaoh** [comment]
@adiati98 Done! Thank you!

**Review by adiati98 — APPROVED** [review]
Well done, @SkipPharaoh! 🙌
Thank you for the changes!

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕 

git merge GIF

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
