### PR TITLE
feat: Add livlaurel as a contributor

### PR DESCRIPTION
**Pull request by livlaurel**
## Description
This PR adds livlaurel as a contributor.

## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [ ] 📝 Documentation Update

## Related Issues

Closes #565

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section

- [x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

DD06956B-EC27-4597-AF1D-8A1DDDB4EF7E_4_5005_c

## [optional] What GIF best describes this PR or how it makes you feel?

vibing

### CODE REVIEW

**Comment by adiati98** [comment]
Hi @livlaurel,
Thank you for your contribution! ✨ 

There's a slight change that you need to make in your PR template.
Can you remove the parentheses from your issue number? Having them would not close the issue automatically when the PR merge. It should be `Closes #565`. 

Thank you. 🙂

**Comment by livlaurel** [comment]
Fixed closes number parentheses

**Comment by livlaurel** [comment]
Done! I just fixed the closes parentheses!

**Review by adiati98 — APPROVED** [review]

**Comment by adiati98** [comment]
@BekahHW can I have the 2nd approval here? Thanks! ✨

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
