### PR TITLE
docs: add @paulrwade as a contributor

### PR DESCRIPTION
**Pull request by paulrwade**
## Description

This PR adds paulrwade as a contributor, as we are encouraged to do in the Intro to Open Source course.

## What type of PR is this? (check all applicable)

- [ x] 🤝 Add a contributor
- [ x ] 📝 Documentation Update

## Related Issues

closes #298 

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [ x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [ x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x ] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

image

### CODE REVIEW

**Review by adiati98 — APPROVED** [review]
Well done, @paulrwade! 🙌
Thank you for the PR! 😄

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕 

git merge GIF

**Comment by paulrwade** [comment]
Now THAT'S a funny merge image, Ayu. LOL.

I wish I could have sent you more $, but cash is low right now while I'm upping my coding game so I can get hired. Thanks again! I gave you Kudos on Twitter. :)

**Comment by adiati98** [comment]
Thanks so much, @paulrwade! ✨ 
I'm very happy that I can help you learn from these contributions.

Looking forward to your next (logo) PR! 🙌🏽

**Comment by paulrwade** [comment]
Will have a PR for that issue soon, Ayu!
😀👍🏻👍🏻

**Pull request merged**
