### PR TITLE
docs: add @overfero as a contributor

### LINKED ISSUE #348: Feature: Add @overfero as a contributor
### Description

As part of the Intro to Open Source course, we are encouraged to contribute to this repo.

### Suggested solution

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

### PR DESCRIPTION
**Pull request by overfero**
## Description

This PR adds @overfero  as a contributor.

## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [x] 📝 Documentation Update

## Related Issues
Closes #348 

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)
image

### CODE REVIEW

**Review by adiati98 — COMMENTED** [review]
Hi @overfero,
Thank you for your contribution! ✨ 

However, please complete your PR template so we can understand the changes you made and the background of this PR. That said, please **fill in the description** in your PR template.

You can read this [blog post](https://dev.to/opensauced/streamline-your-contributions-mastering-issue-forms-and-pr-templates-36j5) to learn the importance of PR templates and how to fill in a PR template.

We're only reviewing this PR once we get all the information needed.
Please let us know once you've completed the form or if you have any question.

Thank you. 🙂

**Comment by overfero** [comment]
thanks  @adi

> Hi @overfero, Thank you for your contribution! ✨
> 
> However, please complete your PR template so we can understand the changes you made and the background of this PR. That said, please **fill in the description** in your PR template.
> 
> You can read this [blog post](https://dev.to/opensauced/streamline-your-contributions-mastering-issue-forms-and-pr-templates-36j5) to learn the importance of PR templates and how to fill in a PR template.
> 
> We're only reviewing this PR once we get all the information needed. Please let us know once you've completed the form or if you have any question.
> 
> Thank you. 🙂

thank you for the correction, i already did a changes, let me know if i miss something

**Comment by adiati98** [comment]
@overfero I don't see any description yet in your PR form.

**Comment by adiati98** [comment]
Hey @overfero,

We have merged a PR before yours. Please **[resolve the conflicts](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=merge-conflicts-in-the-guestbook-repository)** before we can review your PR.

Please let me know if you need any help. Thanks. 😊

**Comment by overfero** [comment]
oh i get it i dont fill the description thanks, im new at this. please review my pull request

**Comment by overfero** [comment]
okay i already generate the README

**Review by adiati98 — APPROVED** [review]
Well done and thank you for your contribution, @overfero! ✨ 

If you haven't, you can join our [Community](https://github.com/orgs/open-sauced/discussions/1) and say hi! 👋🏼 
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕🍴

git merge GIF

**Pull request merged**
