### PR TITLE
Add my profile

### PR DESCRIPTION
**Pull request by Kaz-Smino**
## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [ ] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### How did you add yourself as a contributor?

- [ ] 🤖 With CLI
- [x] ⌨️ Manually

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [ ] ✅ Yes
- [x] ❌ No

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [ ] ✅ Yes
- [x] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @Kaz-Smino! :) Based on your responses, it seems that you have not fully followed the CLI approach to adding your name to the guestbook. Is there something you are struggling with?

**Comment by Kaz-Smino** [comment]
@CBID2 Sorry, my bad. I added my name manually, so I changed the checkbox to add my name.

**Comment by CBID2** [comment]
> @CBID2 Sorry, my bad. I added my name manually, so I changed the checkbox to add my name.

Thanks for clarifying @Kaz-Smino! :) Now you need to do `npm run contributors:generate ` command in your terminal so the guestbook can show up on the README. From there, you need to create a screenshot of your entry. I highly recommend [reading step 8 again](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) to learn how.

**Comment by Kaz-Smino** [comment]
@CBID2 Got it. I'm gonna try to do it one more time. Thank you for sharing.

**Comment by Kaz-Smino** [comment]
@CBID2 Please check [here](https://github.com/open-sauced/guestbook/pull/218) instead of this PR.

**Pull request closed without merging**
