### PR TITLE
fix: Remove duplicate word as a contributor

### PR DESCRIPTION
**Pull request by BekahHW**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by adiati98 — DISMISSED** [review]

**Comment by adiati98** [comment]
@BekahHW is this a fix from your previous PR? If so, I'll merge it in 🙂

**Review by adiati98 — COMMENTED** [review]
@BekahHW 

In line 19:

```yml
if: contains(github.event.pull_request.title, 'as a contributor')
```

Can we add the request title to also contains `'to the guestbook'` as I see some folks write the title with something like "Add {name} to the guestbook"?

**Review by CBID2 — APPROVED** [review]
Looks good

**Comment by CBID2** [comment]
@BekahHW, I accidentally merged this PR. 🤦🏾‍♀️ So, I reverted it in PR #165? Can you merge that please? :)

**Comment by adiati98** [comment]
> @BekahHW, I accidentally merged this PR. 🤦🏾‍♀️ So, I reverted it in PR #165? Can you merge that please? :)

Before you merge that in, I left a [comment here](https://github.com/open-sauced/guestbook/pull/164#pullrequestreview-1704865692) for you to check out, @BekahHW 🙂.

**Pull request merged**
