### PR TITLE
feat: Add JulesRules65 as a contributor

### PR DESCRIPTION
**Pull request by JulesRules65**
## What type of PR is this? (check all applicable)

- [ x ] 🤝 Add a contributor
- [ ] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [ x ] ✅ Yes
- [ ] ❌ Not yet

### How did you add yourself as a contributor?

- [ ] 🤖 With CLI
- [ x ] ⌨️ Manually

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [ x ] ✅ Yes
- [ ] ❌ No

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [ x ] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [ x ] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot

image

### CODE REVIEW

**Comment by BekahHW** [comment]
@JulesRules65 Thanks for your Pull Request! Can you merge the latest changes from the main branch and resolve any conflicts? If you need some help with that, check out this post: [Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h).

**Review by BekahHW — CHANGES_REQUESTED** [review]
Please merge in the latest from main.

**Review by BekahHW — CHANGES_REQUESTED** [review]
Hey there, it looks like there's an issue with the README updating. For everyone who adds themselves to the repo, it updates the number here. Yours isn't updating.

image

Can you try to run `npm run contributors:generate` again?

**Comment by CBID2** [comment]
Also @JulesRules65, don't forget to update your branch.

**Comment by CBID2** [comment]
It looks ok now @BekahHW 
screenshot of updated README

**Comment by JulesRules65** [comment]
Hey, so what's next? Ready for merging isn't it? Or do i have to do anything else?

**Comment by CBID2** [comment]
> Hey, so what's next? Ready for merging isn't it? Or do i have to do anything else?

Hi @JulesRules65. We just need Bekah's response. If she requests changes, you just make them :). Think of making an open source contribution like your cooking your favorite dish. High quality ingredients + attentive cooking techniques + the right temperature = something that nourishes the soul! 
good food-good mood

**Review by CBID2 — APPROVED** [review]
It looks ok on my end

**Review by BekahHW — APPROVED** [review]
Great job, @JulesRules65!

**Comment by JulesRules65** [comment]
> Great job, @JulesRules65!

Thank you @BekahHW :)

**Pull request merged**
