### PR TITLE
feat:  add my name 

### PR DESCRIPTION
**Pull request by Lymah123**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by Lymah123** [comment]
Hi @CBID2 :)!

**Comment by CBID2** [comment]
> Hi @CBID2 :)!

Hi @Lymah123! 😃 You did great in the first part. Now, you just have to follow the other steps to add it to the README:

**Comment by Lymah123** [comment]
> > Hi @CBID2 :)!
> 
> Hi @Lymah123! 😃 You did great in the first part. Now, you just have to follow the other steps to add it to the README:
Alright, thank you!

**Comment by Lymah123** [comment]
I have made update @CBID2 .

**Pull request merged**
