### PR TITLE
feat: Add @nhim-uit as a contributor

### LINKED ISSUE #557: Feature: Add @nhim-uit as a contributor
### Description

As part of the Intro to Open Source course, we are encouraged to contribute to this repo.

### Suggested solution

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

### PR DESCRIPTION
**Pull request by nhim-uit**
## Description

This PR adds @nhim-uit as a contributor.
## What type of PR is this? (check all applicable)

- [X] 🤝 Add a contributor
- [ ] 📝 Documentation Update

## Related Issues
Closes #557 

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section

- [X] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [X] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [X] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

contributor

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hey @nhim-uit,
Thank you for your contribution! ✨ 

We have merged a PR before yours. Please **[resolve the conflicts](https://opensauced.pizza/learn/intro-to-oss/how-to-contribute-to-open-source#merge-conflicts-in-the-guestbook-repository)** before we can review your PR.

Let me know if you have questions or need any help. Thanks. 😊

**Comment by nhim-uit** [comment]
> Hey @nhim-uit, Thank you for your contribution! ✨
> 
> We have merged a PR before yours. Please **[resolve the conflicts](https://opensauced.pizza/learn/intro-to-oss/how-to-contribute-to-open-source#merge-conflicts-in-the-guestbook-repository)** before we can review your PR.
> 
> Let me know if you have questions or need any help. Thanks. 😊

Hi, I've resolved the conflicts and move my info to the bottom of the file. 
Please have a look. 😊

**Comment by adiati98** [comment]
@nhim-uit, have you run the command to generate the README? Because I don't see the badge increasing.

**Comment by nhim-uit** [comment]
> @nhim-uit, have you run the command to generate the README? Because I don't see the badge increasing.

Hi, I've run the command. Please check 😊

**Review by adiati98 — APPROVED** [review]

**Review by BekahHW — APPROVED** [review]

**Comment by adiati98** [comment]
Well done and thank you for your contribution, @nhim-uit! ✨ 

If you haven't, you can join our [Community](https://github.com/orgs/open-sauced/discussions/1).
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕🍴

git merge GIF

**Pull request merged**
