### PR TITLE
feat: Add Ydigit as a contributor

### PR DESCRIPTION
**Pull request by Ydigit**
## What type of PR is this? (check all applicable)

- [X] 🤝 Add a contributor
- [ ] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [X] ✅ Yes
- [ ] ❌ Not yet

### How did you add yourself as a contributor?

- [X] 🤖 With CLI
- [ ] ⌨️ Manually

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [X] ✅ Yes
- [ ] ❌ No

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [X] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [X] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)
screeenshoot

## [optional] What GIF best describes this PR or how it makes you feel?
😀

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hey @Ydigit ,
Thank you for your PR! ✨

We have merged a PR before yours. Please [resolve the conflicts](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=merge-conflicts-in-the-guestbook-repository) before we can review and merge yours.

Also, please fill in the "Description" section and complete the PR form.
Incomplete PR form will be marked invalid.

Do let us know if you need any help. Thanks. 😊

**Comment by Ydigit** [comment]
Hi adiati, is anything missing?, I fixed the conflicts, and the Description part.

**Comment by adiati98** [comment]
@Ydigit I'd like to checking in.
How's the progress here? Do you need any help?

**Comment by adiati98** [comment]
Hey @Ydigit,

We have merged a PR before yours. Please **[resolve the conflicts](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=merge-conflicts-in-the-guestbook-repository)** before we can review and merge yours.



Also, please **fill in the "Description" section** and complete the PR form.

You can do so by editing the PR form:
1. Click the `...` icon on top of the form.
2. Select "Edit".

> [!WARNING]
> Incomplete PR form will be marked invalid and may be close.

Do let us know if you need any help. Thanks. 😊

**Comment by adiati98** [comment]
Hi @Ydigit,

As we don't get any response from you for a while, we're closing this PR.

Feel free to create a new PR to add yourself to the guestbook if you still want to work on it. 🙂 

Thank you.

**Pull request closed without merging**
