### PR TITLE
feat: Add @Firdous2307 as a contributor

### LINKED ISSUE #526: Feature: Add @Firdous2307 as a contributor.
### Description

As part of the intro to Open Sauced, I have decided to contribute and add myself as a contributor.

### Suggested solution

Add me as a contributor.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

### PR DESCRIPTION
**Pull request by Firdous2307**
## Description

This PR adds Firdous2307 as a contributor.

## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [ ] 📝 Documentation Update

## Related Issues

Closes #526 

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

Screenshot (1255)

## [optional] What GIF best describes this PR or how it makes you feel?

hhgf

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hi @Firdous2307,
Thank you for your contribution! ✨ 

However, please complete your PR template so we can understand the changes you made and the background of this PR.

Also, please address [the message of the bot](https://github.com/open-sauced/guestbook/pull/527#pullrequestreview-2364899862) and make sure all checks pass.

We're only reviewing this PR once we get all the information needed.
Please let us know once you've completed the form or if you have any question.

Thank you. 🙂

**Review by adiati98 — APPROVED** [review]
Well done and thank you for your contribution, @Firdous2307! ✨ 

FYI, anything goes inside the comment, between `<!--` and `-->`, will be hidden in the preview mode. I helped you by copy-pasting your description so you can refer to it.

If you haven't, you can join our [Community](https://github.com/orgs/open-sauced/discussions/1).
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕🍴

git merge GIF

**Comment by Firdous2307** [comment]
> Well done and thank you for your contribution, @Firdous2307! ✨
> 
> FYI, anything goes inside the comment, between `<!--` and `-->, will be hidden in the preview mode. I helped you by copy-pasting your description so you can refer to it.
> 
> If you haven't, you can join our [Community](https://github.com/orgs/open-sauced/discussions/1). Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕🍴
> 
> git merge GIF [ git merge GIF ](https://camo.githubusercontent.com/23db979d355fdc1d9da22cff57e8be79add87faecaded90bf82a2fadf6cc6fe1/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f63466b69464d44673369466f492f67697068792e676966) [ ](https://camo.githubusercontent.com/23db979d355fdc1d9da22cff57e8be79add87faecaded90bf82a2fadf6cc6fe1/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f63466b69464d44673369466f492f67697068792e676966)

@adiati98 Thank you for the help!!

**Review by BekahHW — APPROVED** [review]

**Comment by adiati98** [comment]
Hey @Firdous2307,
We've approved your PR and about to merge it. But you closed the PR.
Is there any reason for the closing?

If you'd like us to merge your PR, you can reopen it. 🙂

**Comment by Firdous2307** [comment]
@adiati98 Oh sorry about that, I thought it was already merged that's why I closed it, might have deleted my fork too.

**Comment by adiati98** [comment]
Okay. I can't reopen the PR. Feel free to create a new PR. 🙂

**Comment by Firdous2307** [comment]
> Okay. I can't reopen the PR. Feel free to create a new PR. 🙂

@adiati98 Will do so, thanks!!

**Pull request closed without merging**
