### PR TITLE
feat: made the greeting more personalized

### LINKED ISSUE #239: fix: Make the greeting message more personalized
### Type of feature

🐛 Fix

### Current behavior

I noticed that the message for first-time contributors is not personalized enough, which can make the experience a bit assembly-line-like.

Screenshot of first-time contributor greeting

### Suggested solution

Instead of:
PR_COMMENT="Congratulations on completing Chapter 5 of the Intro to OSS Course with your contribution to this repository! You're almost to the end of the course. Create a [highlight](https://app.opensauced.pizza/feed) of your contribution to our guestbook using the instructions in [chapter 6](https://github.com/open-sauced/intro/blob/main/06-the-secret-sauce.md) and share it with us!"
curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d "{"body":"$PR_COMMENT"}" "[https://api.github.com/repos/${{](https://api.github.com/repos/$%7B%7B) github.repository }}/issues/${{ github.event.pull_request.number }}/comments”

How about:
PR_COMMENT="Congratulations on completing Chapter 5 of the Intro to OSS Course with your contribution to this repository @${{ github.actor }}! You're almost to the end of the course. Create a [highlight](https://app.opensauced.pizza/feed) of your contribution to our guestbook using the instructions in [chapter 6](https://github.com/open-sauced/intro/blob/main/06-the-secret-sauce.md) and share it with us!"
curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d "{"body":"$PR_COMMENT"}" "[https://api.github.com/repos/${{](https://api.github.com/repos/$%7B%7B) github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

It'll make the contributor feel more welcomed.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by CBID2**
## Description
This PR modifies the greeting message. It tags the contributor's name, making them feel welcomed!  
Closes #239 

## What type of PR is this? (check all applicable)

- [ ] 🤝 Add a contributor
- [ ] 📝 Documentation Update
- [x] Feature Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [ ] ✅ Yes
- [ ] ❌ Not yet
- [x] ❌ Not applicable

### How did you add yourself as a contributor?

- [ ] 🤖 With CLI
- [ ] ⌨️ Manually
- [x] ❌ Not applicable

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [ ] ✅ Yes
- [ ] ❌ No
- [x] ❌ Not applicable

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [ ] ✅ Yes
- [ ] ❌ No
- [x] ❌ Not applicable

## Added to documentation?

- [ ] 📜 README.md
- [x] 🙅 no documentation needed

## Screenshot (Required for PR Review)

success of the test

### CODE REVIEW

**Comment by adiati98** [comment]
@CBID2, is it possible for you to provide a screenshot of the generated bot message with this change? Thanks! 🙂

**Comment by BekahHW** [comment]
> @CBID2, is it possible for you to provide a screenshot of the generated bot message with this change? Thanks! 🙂

@CBID2 I think Ayu is asking for the screenshot in action. Could you test it out and show what that would look like in the comments?

**Comment by CBID2** [comment]
> > @CBID2, is it possible for you to provide a screenshot of the generated bot message with this change? Thanks! 🙂
> 
> 
> 
> @CBID2 I think Ayu is asking for the screenshot in action. Could you test it out and show what that would look like in the comments?

Yeah I’ll do that. Thanks for clarifying @BekahHW

**Comment by CBID2** [comment]
Hey @adiati98 and @BekahHW! :) The test was successful. Check it out in the screenshot above

**Comment by BekahHW** [comment]
Looks awesome, @CBID2 🎉

**Review by BekahHW — APPROVED** [review]

**Review by adiati98 — APPROVED** [review]
Yes! Looks great.
Thanks, @CBID2 ! 🚀

**Comment by CBID2** [comment]
Woohoo! 😊

**Pull request merged**
