### PR TITLE
docs: add @gwslingerland as a contributor

### PR DESCRIPTION
**Pull request by gwslingerland**
## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [ ] 📝 Documentation Update

## Related Issues
Solves issue #465 

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)
afbeelding

### CODE REVIEW

**Comment by adiati98** [comment]
> # PR Compliance Checks
> Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project. The results are listed in the following section.
> 
> ## Issue Reference
> In order to be considered for merging, the pull request description must refer to a specific issue number. This is described in our [Contributing Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/). This check is looking for a phrase similar to: "Fixes #XYZ" or "Resolves #XYZ" where XYZ is the issue number that this PR is meant to address.

Hi @gwslingerland,
Thank you for your contribution! ✨

Can you please address above message until all checks pass?

Also, we have merged a PR before yours. You need to [resolve the conflicts](https://opensauced.pizza/learn/intro-to-oss/how-to-contribute-to-open-source#merge-conflicts-in-the-guestbook-repository) before we can review your PR.

Let me know if you need any help. Thanks. 😊

**Comment by gwslingerland** [comment]
i resolved the issues in my forked repo. Do i need to create a new pull-request or is it automatically updated?

**Comment by adiati98** [comment]
> i resolved the issues in my forked repo. Do i need to create a new pull-request or is it automatically updated?

Hi @gwslingerland,
You don't need to create new PR. It's automatically updated once you pushed your changes.

However, there are some issues that need to be fixed here:

- Some contributors' profile are deleted here and we don't want that.
- You haven't removed the opening and closing `===` that mark the conflicts on the README.
- You haven't run the command to generate the profile after resolving the conflicts. Once you run this, the badge should increase.

Another thing is, the check is still not passed because you use the word `Solves issue` before your issue number. The keyword rule for GitHub is strict. So you need to use the keyword `Resolves` follow by your issue number.

What you can do to resolve conflicts:

- Undo the pushed commit to before you resolved the conflicts. You can read [this blog post](https://dev.to/github/how-to-undo-pushed-commits-with-git-2pe6) to do that.
- Please read through the instructions to resolve the conflicts in this repo as I linked in my [previous comment](https://github.com/open-sauced/guestbook/pull/466#issuecomment-2351157845).

Do let me know if you have questions. Thanks. ✨

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hi @gwslingerland,
Answering your question, you don't need to create new PR. It's automatically updated once you pushed your changes.

However, there are some issues that need to be fixed here:

- Some contributors' profile in `.all-contributorsrc` file are deleted and we don't want that.
- You haven't removed the opening and closing `===` that mark the conflicts on the README.
- You haven't run the command to generate the profile after resolving the conflicts. Once you run this, the badge should increase.

Another thing is, the check is still not passed because you use the word `Solves issue` before your issue number. The [keyword rule](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for GitHub is strict. So you need to use the keyword `Resolves` follow by your issue number.

What you can do to resolve conflicts:

- Undo the pushed commit to before you resolved the conflicts. You can read [this blog post](https://dev.to/github/how-to-undo-pushed-commits-with-git-2pe6) to do that.
- Please read through the instructions to resolve the conflicts in this repo as I linked in my [previous comment](https://github.com/open-sauced/guestbook/pull/466#issuecomment-2351157845).

Do let me know if you have questions. Thanks. ✨

**Comment by adiati98** [comment]
Hey @gwslingerland,

As your PR hasn't been addressed for some time, we're closing it.
Feel free to open a new issue and PR, and work on it if you'd still like to contribute. ✨

**Pull request closed without merging**
