### PR TITLE
docs: add @tedashikode as a contributor

### PR DESCRIPTION
**Pull request by tedashikode**
## Description
This PR adds me as a contributor to the guest with the following contributions: code, doc, example, ideas and research. I want to do this to work on real world projects, improve my problem solving skills and become a better programmer.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by tedashikode** [comment]
request to be added to the contributors list

**Comment by CBID2** [comment]
> request to be added to the contributors list

Hi @tedashikode! :) There's some merge conflicts on your branch, so I recommend checking out [this article](https://www.alphr.com/vs-code-open-merge-editor/) to aid with that.

**Comment by tedashikode** [comment]
HI @CBID2, I think I've been able to resolve the conflict.

**Comment by CBID2** [comment]
> Hi @CBID2, I think I've been able to resolve the conflict.

Great @tedashikode! :) I highly recommend filling out the issue too. This is a crucial skill when contributing to open source projects because it would help maintainers gain a better understanding of what you're adding to their project.

**Comment by tedashikode** [comment]
> > Hi @CBID2, I think I've been able to resolve the conflict.
> 
> Great @tedashikode! :) I highly recommend filling out the issue too. This is a crucial skill when contributing to open source projects because it would help maintainers gain a better understanding of what you're adding to their project.

**Comment by CBID2** [comment]
Why did you close your pull request @tedashikode?

**Comment by tedashikode** [comment]
> Why did you close your pull request @tedashikode?

It was a mistake. I'm having a surprisingly difficult time figuring this out😂

**Comment by tedashikode** [comment]
> > > Hi @CBID2, I think I've been able to resolve the conflict.
> > 
> > 
> > Great @tedashikode! :) I highly recommend filling out the issue too. This is a crucial skill when contributing to open source projects because it would help maintainers gain a better understanding of what you're adding to their project.

You recommended filling out the issue too. I think I already did that...

**Comment by CBID2** [comment]
Sorry @tedashikode  I meant to say pull request form. 🤦🏾‍♀️

**Comment by tedashikode** [comment]
> Sorry @tedashikode I meant to say pull request form. 🤦🏾‍♀️

Okay, no worries. What type of PR does me adding my name to the contributors list fall under then?

**Comment by tedashikode** [comment]
I've filled the PR form.

**Comment by CBID2** [comment]
> I've filled the PR form.

It's still empty @tedashikode 
Screenshot 2023-09-23 at 5 02 50 PM

**Comment by tedashikode** [comment]
> > I've filled the PR form.
> 
> It's still empty @tedashikode Screenshot 2023-09-23 at 5 02 50 PM

Documentation Update,  no, because they aren't needed and no documentation needed boxes have been checked though. I think you missed them because you're in dark mode

**Comment by CBID2** [comment]
Ok now you just have to fill out the description section. Do something like this:

"This PR [adds/fixes/updates]"

**Comment by tedashikode** [comment]
> Ok now you just have to fill out the description section. Do something like this:
> 
> "This PR [adds/fixes/updates]"

Okay, I've done that.

**Comment by CBID2** [comment]
> > Ok now you just have to fill out the description section. Do something like this:
> 
> > 
> 
> > "This PR [adds/fixes/updates]"
> 
> 
> 
> Okay, I've done that.

Well done @tedashikode! :) Now, all you need is a thumbs up from @BekahHW, so she can merge your PR

**Comment by tedashikode** [comment]
> > > Ok now you just have to fill out the description section. Do something like this:
> > 
> > 
> > > 
> > 
> > 
> > > "This PR [adds/fixes/updates]"
> > 
> > 
> > Okay, I've done that.
> 
> Well done @tedashikode! :) Now, all you need is a thumbs up from @BekahHW, so she can merge your PR

Okay, thank you so much.

**Review by BekahHW — APPROVED** [review]

**Comment by tedashikode** [comment]
@CBID2 Yayyyyyyy, thanks a lot😊😅

**Comment by CBID2** [comment]
> @CBID2 Yayyyyyyy, thanks a lot😊😅

Anytime @tedashikode! 😊

**Pull request merged**
