### PR TITLE
Add safacade009

### PR DESCRIPTION
**Pull request by safacade009**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by BekahHW** [comment]
Hey @safacade009. You had some merge conflicts and we've merged in some PRs since yours. Can you merge in the latest from main and resolve your merge conflicts? Let me know if you have any questions.

**Comment by CBID2** [comment]
@safacade009, we merged some PRs recently. Can you solve the merge conflicts in your branch? If you need a refresher, check out the blog post,[Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h)

**Comment by CBID2** [comment]
@safacade009, are you still working on this?

**Review by adiati98 — APPROVED** [review]
Hi @safacade009,
We've resolved the merge conflicts and merged your PR! 🎉

Check out [this section about how to resolve conflicts](https://github.com/open-sauced/guestbook#keeping-branch-up-to-date-and-resolving-merge-conflicts) for your future reference.

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕

pizza GIF

**Pull request merged**
