### PR TITLE
Update intro_course_contributor.yml to remove repeat messages

### LINKED ISSUE #187: Bug: message repeats when contributor edits PR
### Describe the bug

Our bot is overly aggressive.

image

### Steps to reproduce

See this PR https://github.com/open-sauced/guestbook/pull/180

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by BekahHW**
## Description

closes #187 
## What type of PR is this? (check all applicable)

- [ ] 🤝 Add a contributor
- [ ] 📝 Documentation Update
- [x] bug fix

## Contributors checklist (check all applicable)

- Have you read the [Getting Started](https://github.com/open-sauced/guestbook#getting-started) section thoroughly?

  - [x] ✅ Yes
  - [ ] ❌ Not yet

- How did you add yourself as a contributor?

  - [ ] 🤖 With CLI
  - [ ] ⌨️ Manually

    If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

    - [ ] ✅ Yes
    - [ ] ❌ No

- Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
  - [ ] ✅ Yes
  - [ ] ❌ No

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by CBID2** [comment]
> @BekahHW is there any way for me to test this workflow or we can just merge it in and see what happen?

Check this out @adiati98: https://github.com/nektos/act

**Comment by BekahHW** [comment]
@CBID2 it won't break anything, so I think it's fine to merge and find out.

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
> @CBID2 it won't break anything, so I think it's fine to merge and find out. 

Merged it @BekahHW

**Pull request merged**
