### PR TITLE
docs: Added information to write PR details outside the comments

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
issue #521

### CODE REVIEW

**Comment by Brijeshthummar02** [comment]
@adiati98 is it okay now?

**Comment by adiati98** [comment]
@Brijeshthummar02 no, it's not. Have you checked other PRs to see how they look like?

**Comment by Brijeshthummar02** [comment]
suggest me specific changes to go with.

**Comment by adiati98** [comment]
@Brijeshthummar02, I'd like to know something. When you opened this PR, did you delete the whole template? If so, you shouldn't do that. You need to fill the sections that are related to your PR and you may leave the others (that are not related) blank.

**Comment by Brijeshthummar02** [comment]
yes i by mistake deleted the whole template, so should i edit edit this pr template or need to create complete new pr with keeping evrything in mind.

**Comment by Brijeshthummar02** [comment]
in resolve to it, i'm opening new pr.

**Pull request closed without merging**
