### PR TITLE
feat: Add @SimonGideon as a contributor

### LINKED ISSUE #267: Feature:
### Description

As part of the Intro to Open Source course, we are encouraged to contribute to this repo.

### Suggested solution

Add myself as a contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

### PR DESCRIPTION
**Pull request by SimonGideon**
## Description
In this PR I add myself as a contributor in the readMe markdown.

## What type of PR is this? (check all applicable)

- [X] 🤝 Add a contributor
- [ ] 📝 Documentation Update

## Related Issues
Closes #267 

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [X] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [X] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [ ] 📜 README.md
- [X] 🙅 no documentation needed

## Screenshot (Required for PR Review)
Screenshot from 2024-04-30 19-35-48

## [optional] What GIF best describes this PR or how it makes you feel?
image

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hi @SimonGideon,
Thank you for your PR! 🙌

However, please complete your PR form so we can understand and review the changes you made.

Can you please:
- make sure you fill all the areas in the form,
- provide a **description** of the changes that you made.

Also, please **add keyword `Closes`** before your PR number, e.g: `Closes #000`. Adding this keyword will automatically close your issue as completed once it's merged.

We're only reviewing and accepting this PR once we get all the information needed.
Please let us know once you've completed the form.

Thank you! 🙂

**Comment by adiati98** [comment]
Hey @SimonGideon,

Sorry if my instruction wasn't clear.
What I mean was please add keyword **Closes** before your PR number **in the Related Issues** section — e.g: Closes #XXX — and not the title.

**Comment by SimonGideon** [comment]
@adiati98 😄 Thanks for making it clear. I have made the changes as requested.

**Review by adiati98 — APPROVED** [review]

**Review by BekahHW — APPROVED** [review]

**Comment by ThembaMahlangu** [comment]
How does one contribute too?

**Pull request merged**
