### PR TITLE
Add J to the guestbook

### PR DESCRIPTION
**Pull request by bellsofaba**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by bellsofaba** [comment]
Added my details to the guestbook.

**Review by BekahHW — CHANGES_REQUESTED** [review]
I'm not sure how you adding yourself here, but a couple of things:
1. It says that 740 lines were added. Make sure you're only adding your object and that the other code isn't touched.
2. Did you run `npm run contributors:generate`? That has to be run to ensure that that README gets updated with your profile.

**Comment by bellsofaba** [comment]
> I'm not sure how you adding yourself here, but a couple of things:
> 
> 1. It says that 740 lines were added. Make sure you're only adding your object and that the other code isn't touched.
> 2. Did you run `npm run contributors:generate`? That has to be run to ensure that that README gets updated with your profile.

I did. But I keep getting the following response from my terminal

**Comment by bellsofaba** [comment]
> I'm not sure how you adding yourself here, but a couple of things:
> 
> 1. It says that 740 lines were added. Make sure you're only adding your object and that the other code isn't touched.
> 2. Did you run `npm run contributors:generate`? That has to be run to ensure that that README gets updated with your profile.

Somewhere along the line somethings got replicated but I have deleted the repetitions and ran the npm run contributors:generate command

**Pull request closed without merging**
