### PR TITLE
Add my info to contributions list

### PR DESCRIPTION
**Pull request by Ezzywealth**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by BekahHW** [comment]
We've merged in some PRs since you made yours, so you'll need to merge the latest changes into your branch.

**Comment by BekahHW** [comment]
Hey @Ezzywealth can you merge in the latest changes to the main branch? If you need help, let me know.

**Review by adiati98 — APPROVED** [review]
Hi @Ezzywealth,
We've resolved the merge conflicts and merged your PR! 🎉

Check out [this section about how to resolve conflicts](https://github.com/open-sauced/guestbook#keeping-branch-up-to-date-and-resolving-merge-conflicts) for your future reference.

Also, in the future, please complete the PR form and describe the changes clearly. Doing so will help maintainers to review and understand the changes in your PR, and will it benefit you as well. 🙂

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕

pizza GIF

**Comment by Ezzywealth** [comment]
hi @adiati98 
My sincere apologies
For some reasons, I didn't see that I am been tagged.
Dealing with so many things, I think I need to take things slow.

@BekahHW @CBID2 , My silence wasn't deliberate.
My sincere apologies.

**Comment by adiati98** [comment]
No worries at all, @Ezzywealth! 🙂

**Pull request merged**
