### PR TITLE
docs: add @at-the-vr as a contributor

### PR DESCRIPTION
**Pull request by at-the-vr**
## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [ ] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### How did you add yourself as a contributor?

- [x] 🤖 With CLI
- [ ] ⌨️ Manually

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [ ] ✅ Yes
- [ ] ❌ No
- [x] NA

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [ ] ✅ Yes
- [ ] ❌ No
- [x] NA

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot
image

## [optional] What GIF best describes this PR or how it makes you feel?
image

### CODE REVIEW

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hi @at-the-vr! :) Your PR looks great so far. Since you used the CLI tool, you need to do run the `npm run contributors:add` command in your terminal. If you're still stuck, reread the [Let's Get Practical Section](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=let39s-get-practical) in our intro course.

**Comment by at-the-vr** [comment]
> Hi @at-the-vr! :) Your PR looks great so far. Since you used the CLI tool, you need to do run the `npm run contributors:add` command in your terminal. If you're still stuck, reread the [Let's Get Practical Section](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=let39s-get-practical) in our intro course.

I actually ran the `add` cmd and that's what the changes are right now. do i need to run it again ?

**Comment by CBID2** [comment]
> > Hi @at-the-vr! :) Your PR looks great so far. Since you used the CLI tool, you need to do run the `npm run contributors:add` command in your terminal. If you're still stuck, reread the [Let's Get Practical Section](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=let39s-get-practical) in our intro course.
> 
> 
> 
> I actually ran the `add` cmd and that's what the changes are right now. do i need to run it again ?
> 
> edit: I don't see visible changes unless I change my contribution types

Hi @at-the-vr. That would probably be best. @adiati98 and @BekahHW, what do you think? 🤔

**Comment by at-the-vr** [comment]
Just pushed a new commit (removing 1 type from my profile).

**Comment by adiati98** [comment]
@at-the-vr thank you for the PR. You can add the type of contributions as much as you like. So you don’t need to remove anything if you don't want to. 🙂

I think what's confusing here is that you put "n/a" in the "Have you run `npm run contributors:generate` to generate your profile and the badge on the README?" section.

If you have run the command, then you should tick yes.

In the future, you might want to pay attention to the details of your PR. Most of the time, maintainers will read your PR form to understand the changes before they have time to review and test your changes.

I'm not on my computer today, so I'll check this tomorrow. 👍

**Comment by at-the-vr** [comment]
> @at-the-vr thank you for the PR. You can add the type of contributions as much as you like. So you don’t need to remove anything if you don't want to. 🙂
> 
> I think what's confusing here is that you put "n/a" in the "Have you run `npm run contributors:generate` to generate your profile and the badge on the README?" section.
> 
> If you have run the command, then you should tick yes.
> 
> In the future, you might want to pay attention to the details of your PR. Most of the time, maintainers will read your PR form to understand the changes before they have time to review and test your changes.
> 
> I'm not on my computer today, so I'll check this tomorrow. 👍

gotta clarify, I didn't ran the `generate` command cuz `add` covered everything. Running `generate` creates 0 changes or commits in my PR 🤔

**Review by adiati98 — APPROVED** [review]
Thank you and well done, @at-the-vr! 🙌

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕 

git merge GIF

**Review by CBID2 — APPROVED** [review]
LGTM

**Pull request merged**
