### PR TITLE
docs: add @jayasuryard31 as a contributer

### PR DESCRIPTION
**Pull request by jayasuryard31**
Adding a new branch as a contributer

### CODE REVIEW

**Comment by BekahHW** [comment]
Thanks for your PR. It looks like you haven't run `npm run contributors:generate` after adding yourself to the repo. Please run that command in your branch, commit, and push your updates. Let us know when you're ready for a new review!

**Comment by jayasuryard31** [comment]
> Thanks for your PR. It looks like you haven't run `npm run contributors:generate` after adding yourself to the repo. Please run that command in your branch, commit, and push your updates. Let us know when you're ready for a new review!

thank you for reviewing.

**Review by CBID2 — APPROVED** [review]
Well done @jayasuryard31! :) As a tip, use more descriptive titles for your pull request(e.g., `docs: add [your name]`). It'll help maintainers gain a better understanding of your contribution.

**Comment by jayasuryard31** [comment]
> Well done @jayasuryard31! :) As a tip, use more descriptive titles for your pull request(e.g., `docs: add [your name]`). It'll help maintainers gain a better understanding of your contribution.

"NOTED" thank you for the tip, I'll remember this in my next commit.

**Comment by CBID2** [comment]
> > Well done @jayasuryard31! :) As a tip, use more descriptive titles for your pull request(e.g., `docs: add [your name]`). It'll help maintainers gain a better understanding of your contribution.
> 
> "NOTED" thank you for the tip, I'll remember this in my next commit.

You can do it now too @jayasuryard31! :) Just click on the edit button that's near your PR form.

**Pull request merged**
