### PR TITLE
Docs fix link in the issue template #271

### PR DESCRIPTION
**Pull request by prasad-hp**
## What type of PR is this? (check all applicable)

- [ ] 🤝 Add a contributor
- [x] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [ ] 📜 README.md
- [x] 🙅 no documentation needed

## Screenshot (Required for PR Review)
Screenshot from 2024-05-09 22-14-47

### CODE REVIEW

**Comment by prasad-hp** [comment]
Hi @adiati98 ,

Thank you for your feedback and guidance. 
I understand the issues you've raised, and I will address them accordingly.
I'll make the necessary adjustments and submit the new PRs.

**Comment by prasad-hp** [comment]
Hi @adiati98 
I just have one doubt, I have fixed the URL link issue, so during raising the PR in the Template should I respond to the Contributors checklist, because during raising this PR I would not have added myself to contributors. 
Thank You 🙂
Best Regards
Prasad

**Comment by adiati98** [comment]
You don't need to fill in those checklists for the fix. 🙂

But please make sure to fill in the description and the link to the issue in the "Related Issues" section.

**Comment by prasad-hp** [comment]
Thank you for the quick response! I've created a new PR with updated URL Link. I've also made sure to follow the provided format for the PR template and have addressed the issues raised in your review.

As someone new to open source, it's truly heartening to receive such positive support from the community. I'm grateful for the guidance provided and eager to continue contributing.

Thank you once again for your help! 🙂

**Pull request closed without merging**
