### PR TITLE
Adds Mi1king to the guestbook

### PR DESCRIPTION
**Pull request by Mi1king**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [x] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [x] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by Mi1king** [comment]
feat: add {GitHub username} as a contributor

**Comment by CBID2** [comment]
Thanks for your Pull Request @Mi1king! We've merged in some new PRs since you submitted. Can you merge the latest changes and resolve conflicts? If you need some help with that, check out [this section of our Contributing Guide](https://github.com/open-sauced/guestbook#resolving-merge-conflicts).

**Comment by Mi1king** [comment]
> Thanks for your Pull Request @Mi1king! We've merged in some new PRs since you submitted. Can you merge the latest changes and resolve conflicts? If you need some help with that, check out [this section of our Contributing Guide](https://github.com/open-sauced/guestbook#resolving-merge-conflicts).

Hi @CBID2, I just commit "Resolve merge conflicts" and push it to my brance. Is this contribution done?

**Review by CBID2 — APPROVED** [review]
Merge time! :)

**Pull request merged**
