### PR TITLE
docs: add @JayRKyd as a contributor

### PR DESCRIPTION
**Pull request by JayRKyd**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Please do not leave this blank 
This PR adds  JayRKyd to the guestbook. 

 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by BekahHW** [comment]
Hey Jay! 

This looks great. There is an issue with two contributors being deleted from the main branch with your PR. I think it was caused by something happening in the main repo. Could you update your branch and merge in the changes from main? Then I should be able to merge this in.

If you have any questions, let me know!

**Comment by JayRKyd** [comment]
Hey! okay uhh a quick question. how do i update my branch and merge it?

**Comment by jpmcb** [comment]
@JayRKyd - with your local branch checked out, try `git pull --rebase`. That should pull the latest changes from the `main` branch and update your local branch to reflect those changes ontop of `main`.

If you're using a Git user interface, there should be a way to pull your changes locally from this repo.

Once you have those changes from `main` on your local branch, push it up to `JayRKyd/guestbook` and that should update it here as well.

**Review by BekahHW — CHANGES_REQUESTED** [review]
Can you merge the changes from the main branch into your forked copy?

**Pull request merged**
