### PR TITLE
docs: remove local project setup from `CONTRIBUTING.md`

### LINKED ISSUE #208: Docs: Remove the "Running the Project Locally" from Contributing Guide
## Description

The content in the [Running the Project Locally](https://github.com/open-sauced/guestbook/blob/main/CONTRIBUTING.md#running-the-project-locally) section in the Contributing Guide is meant for the `intro` repo.

This project is not built on Docsify.

## Suggested solution

Remove the section from the Contributing Guideline.

Below are the code blocks for this section:

https://github.com/open-sauced/guestbook/blob/d2629d634f9df8f973b178d962bd98dcd58ab2df/CONTRIBUTING.md?plain=1#L37-L76

### PR DESCRIPTION
**Pull request by at-the-vr**
## Description
- Closes #208 
- removes "Running the Project Locally" section from [`CONTRIBUTING.md`](https://github.com/open-sauced/guestbook/blob/d2629d634f9df8f973b178d962bd98dcd58ab2df/CONTRIBUTING.md?plain=1#L37-L76)

## What type of PR is this? (check all applicable)

- [ ] 🤝 Add a contributor
- [x] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### How did you add yourself as a contributor?

- [ ] 🤖 With CLI
- [ ] ⌨️ Manually
- [x] NA

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [ ] ✅ Yes
- [ ] ❌ No
- [x] NA

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [ ] ✅ Yes
- [ ] ❌ No
- [x] NA

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed
- [x] NA

### CODE REVIEW

**Comment by adiati98** [comment]
@at-the-vr we just merged a PR before yours.
Can you please resolve the conflicts before we can review and merge this PR?
Here is a resource to [resolve conflicts](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h) to help you.

Let me know if you need any help.
Thank you!

**Comment by at-the-vr** [comment]
got it 👍

**Review by adiati98 — APPROVED** [review]
Thank you, @at-the-vr! 🙌 

This looks good to me.
I would love to get additional review and approval here. 👍

**Review by CBID2 — APPROVED** [review]
Well done @at-the-vr! :) If you want to do more contributions, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo. Also, join our [Discord community](https://discord.gg/opensauced)to get more updates about OpenSauced.

**Pull request merged**
