### PR TITLE
docs: add @goobric as a contributor

### PR DESCRIPTION
**Pull request by goobric**
## Description
add goobric to the guestbook

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by adiati98** [comment]
HI @goobric,
We've merged a PR before yours.
I have merged the updated `main` branch into your working branch.

Please pull the changes into your working branch, run `npm run contributors:generate`, and push it.

**Comment by goobric** [comment]
Hi Adiati98
I have pulled my repo 'goobric:aboutme'
then, ran 'npm run contributors:generate'
states 'all-contributors: not found'
states 'nothing to commit'
231009_guestbook_opendsauce

**Comment by adiati98** [comment]
@goobric, you first need to update your forked repo before you pull the changes.

- Go to your forked repo. 
- Click the "Sync fork" button and then "Update branch".
- Go to your local working branch and run `git pull origin main`.

Then, follow the rest of the steps that I've mentioned.

**Comment by goobric** [comment]
@adiati98 
thank you for your instructions
I don't know if I am doing branch update incorrectly!
This is the screen image from my fork, when I try and sync
231009_guestbook_opendsauce2

**Comment by goobric** [comment]
I am using VSCode, my forked repo is open, I have:
git remote add upstream https://github.com/open-sauced/guestbook.git
git branch -a
git fetch upstream
npm run contributors:generate
git commit -am "aboutme"
git push

Please see attached screen image, and explain what I am doing wrong. Thank you 
231009_guestbook_opendsauce3

**Comment by goobric** [comment]
git merge upstream/main
returns
'Already up-to-date'

**Comment by adiati98** [comment]
@goobric, you're on the right track 😊

Your branch is two commits ahead of the `main` branch because you have commits of adding yourself to the `all-contributorsrc`, and generating your profile and updating the badge on the README.

What you have to do now is to update the badge, which has to be done with `npm run contributors:generate`.

- Go to your local working branch and run `git pull origin main`.
- Run `npm run contributors:generate`.
- Run `git log`. See if there is an automated commit message as the latest commit. Before this one, it should be my (adiati98) commit to merge `main` to your branch.
- If there is an automated commit message, you can push it to the remote repo. If my commit is the latest one, commit your changes, then push it.

**Comment by adiati98** [comment]
> I am using VSCode, my forked repo is open, I have: git remote add upstream https://github.com/open-sauced/guestbook.git git branch -a git fetch upstream npm run contributors:generate git commit -am "aboutme" git push
> 
> Please see attached screen image, and explain what I am doing wrong. Thank you 231009_guestbook_opendsauce3

I was on my phone and I think I missed to see this one.
You don't need to fetch the `upstream` because you've synced your forked (`origin`) repo with the `upstream`.
You should now be able to pull the changes from your forked to your local repo as I mentioned in previous comment.

**Comment by adiati98** [comment]
Hey @goobric 

So, I've pulled your branch from your forked repo and tried out locally.
If you your local branch is synced with your forked repo, then you can follow the steps in my screenrecord here.

To know that your local branch is synced with your forked repo, run `git log` and see the latest commit.
If you see below commit, then it's up-to-date.

```bash
commit 7abc3d613e1d33d7c301385a196aa0993fa89c93 (HEAD -> aboutme, goobric/aboutme)
Merge: 0a2c389 76f5377
Author: Ayu Adiati <45172775+adiati98@users.noreply.github.com>
Date:   Sun Oct 8 17:24:53 2023 +0200

    Merge branch 'main' into aboutme
```

---

Please pay attention that the badge number is changed from 55 to 56.

goobric

**Comment by goobric** [comment]
hi @adiati98 
thank you so much for dedicated all of this time to support and assist me; it is very much appreciated.
I am somewhat confused as to why this process is so challenging and confusing to do!!
I need a lesson on how to correctly use the Git Ecosystem from you :-)
Using my local repo stored on my computer I have:
- git pull origin main
- npm run contributors: generate
- git commit (Your branch is up-to-date with 'origin/aboutme' / nothing to commit, working tree clean)
- git push
- git mergetool (no files need merging)
Now I am really confused! 
Maybe I should just delete my local repo from my computer, and clone the repo from github; and try again.
231009_guestbook_opendsauce5

**Comment by goobric** [comment]
hi @adiati98 
I deleted my local repo from my computer; restarted my computer; cloned the forked repo from my github account; and started again. And did the following:
- npm install
- created a new branch 'aboutme'
- updated the .all-contributorsrc manually
- git commit -am "aboutme goobric"
- git log  (returned: HEAD -> aboutme ; Author: mlaane ; Date: Tue Oct 10 ; aboutme goobric )
- git log --oneline [ returned: 6192347 ( HEAD -> aboutme ) aboutme goobric
- git push -u origin aboutme [ rejected ]
- git pull ( no tracking info for current branch, specify which branch to merge )

I must admit, this experience is not enjoyable :-(  and if other beginners, and people new to tech, have a similar experience; this will be very demoralising and off-putting.
231010_guestbook_opendsauce7
231010_guestbook_opendsauce8

**Comment by goobric** [comment]
@adiati98 
maybe I should start a fresh; completely delete the forked repo on my github account; delete the cloned repo stored locally on my computer; and attempt to try again; by forking the current main branch from the open-sauced:main
May I ask, does this type of issue/challenge with Git & Github normally occur?
If so, having a lesson on solution finding, for this type of issue would be very beneficial. 
I can not believe, I have taken nearly two hours just to contribute a few lines to a json file, to submit to a github project; yet on multiple occurrences it has failed!

**Comment by adiati98** [comment]
> @adiati98 maybe I should start a fresh; completely delete the forked repo on my github account; delete the cloned repo stored locally on my computer; and attempt to try again; by forking the current main branch from the open-sauced:main May I ask, does this type of issue/challenge with Git & Github normally occur? If so, having a lesson on solution finding, for this type of issue would be very beneficial. I can not believe, I have taken nearly two hours just to contribute a few lines to a json file, to submit to a github project; yet on multiple occurrences it has failed!

@goobric, feel free to close this PR and start fresh!

Answering your question, updating your branch and/or resolving merge conflicts before a PR can be merged is common in open source.
So, practicing to update branch and resolve conflicts would be beneficial for you in the future.
This [Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h) might help you to familiar yourself with it.

**Comment by goobric** [comment]
thanks again @adiati98 
thanks for the link to 'Keeping Your Branch Up to Date'
I have deleted the forked repo, from my github account. I will start again from zero.
have a great day.
231010_guestbook_opendsauce9

**Pull request closed without merging**
