### PR TITLE
docs: add @Lor1138 as a contributor

### PR DESCRIPTION
**Pull request by Lor1138**
## Description
This PR adds Lor1138 to the guestbook

## What type of PR is this? (check all applicable)

- [X] 🤝 Add a contributor
- [ ] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [ X] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [X ] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [ ] 📜 README.md
- [X ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

Screenshot 2024-05-02 at 9 14 21 PM

## [optional] What GIF best describes this PR or how it makes you feel?
<iframe src="https://giphy.com/embed/hZj44bR9FVI3K" width="396" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/funny-seinfeld-yay-hZj44bR9FVI3K">via GIPHY</a></p>

### CODE REVIEW

**Comment by Lor1138** [comment]
Thank you for the opportunity to flex my open source muscles!

**Review by adiati98 — COMMENTED** [review]
Hey @Lor1138,
Thanks for the PR! ✨

This is not a blocker, but can you please fill in the description in the PR form?

For your future reference, completing the PR form is necessary for maintainers to understand the changes you made and it can streamline the review process.

Thank you! 😊

**Comment by Lor1138** [comment]
What else should I put into the description? I followed the directions. hmmm

**Comment by CBID2** [comment]
> What else should I put into the description? I followed the directions. hmmm

Put "This PR adds [insert your name here] to the guestbook" @Lor1138.

**Comment by adiati98** [comment]
> What else should I put into the description? I followed the directions. hmmm

Hey @Lor1138,

Understanding and filling in PR templates is more tricky than issues because they only allows to be shown in the format of Markdown instead of form as in issues. 😅

Here are the tricks that I hope can help you in the future!

When looking at a PR template:

1. **Look at the headings/subtitles**. Usually, PR templates have headings (those with `#` symbol) of sections that you need to fill in.
2. Read the **comment outs** carefully. Instructions in PR templates are commonly written in comment outs in every section. And this is what often get missed. In this beginner repo, we've provided an example of what to fill in the comment outs as you can see in below screenshot.
   
Screenshot 2024-05-04 084441

If there is no instructions to be found, pay attention to all headings and fill them in as much as you can. If you don't know what to fill, after you create your PR, ask the maintainers by leaving a comment.

I hope this helps! Feel free to reach out to me if you have any question or need help! 😄

**Comment by Lor1138** [comment]
Thank you for the detailed instructions! I figured it out, I really appreciate the clarification.

**Review by adiati98 — APPROVED** [review]
Hi @Lor1138,
We've helped you resolve the merge conflicts in your PR. ✨ 

Check out [this section about how to resolve conflicts](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=keeping-branches-up-to-date) for your future reference.

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕

pizza GIF

**Pull request merged**
