### PR TITLE
docs: add @MidhaShrey as a contributor

### PR DESCRIPTION
**Pull request by MidhaShrey**
## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [x] 📝 Documentation Update

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [x] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [x] ✅ Yes
- [x] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hey @MidhaShrey,

You opened two PRs (#509 & #510) and both are incomplete.
We only need one PR to add yourself to the guestbook. So, you must choose one (and close the other one) and fix it, or close both and create a new PR for your contribution.

You also need an issue to accompany your PR.

Please read our [contributing guidelines](https://github.com/open-sauced/guestbook/blob/main/CONTRIBUTING.md) carefully to contribute to this repository.
Thank you. 🙂

**Comment by MidhaShrey** [comment]
Hi @adiati98, have closed PR#509. Furthermore have created an issue #511 for this. Thanks, Please do let me know what more needs to be done.

**Comment by adiati98** [comment]
@MidhaShrey as I mentioned in the previous comment, you need to read our [contributing guidelines](https://github.com/open-sauced/guestbook/blob/main/CONTRIBUTING.md) before contributing to this repository.

**Review by BekahHW — CHANGES_REQUESTED** [review]
Please be sure to follow the directions before submitting your PR.

**Comment by adiati98** [comment]
Hey @MidhaShrey,

As your PR hasn't been addressed on for some time, we're closing it.
Feel free to open a new issue and work on it if you'd still like to contribute. And please read our contributing guidelines. ✨

**Pull request closed without merging**
